### ISSUE TITLE
Add standard comment header to each file

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/CasseroleLib#4]
We're a bit inconsistsant with how our headers look now
Ensure each code file has a consistant header which include the following data:

Robot Casserole Common Libraries
Year(s) developed
Class name
description
any other info already in header
Change log

**Comment by imdunne8** [comment]
We should leave out change logs from headers/comments.  That's what version control is for.  Descriptions/documentation within a comment header should be kept very short.  If more than a few sentences are needed it should be made into a wiki page or a documentation page included in the repo.

**Comment by gerth2** [comment]
Fine by me. I derived that list from my employer's C code standards, which
definitely do not cover the same exact space we do :)

**Comment by gerth2** [comment]
Even better, let's scope creep this (for a good cause):

http://www.javapractices.com/topic/TopicAction.do?Id=60

Update all files to have proper javadoc syntax. It will make any user feel
warm and fuzzy that this is good software!

**Comment by gerth2** [comment]
Bonus points: Publish the resulting javadoc to another folder in the repo
to have some nice HTML reference pages for our software libraries

**Comment by imdunne8** [comment]
I figured that last part was from working with old work code.  Basically, if you look up anything about why people leave version history in the comments (while they're using version control) you'll find exactly your reason for about every case and nobody really has any other valid reason.

Anyways, JavaDoc would be nice for something like this where we expect that some other teams might want to use it.  Eclipse creates the comment formatting for you automatically (put a /*\* directly above a method or class and press enter) and there's a menu option to auto generate the HTML.

**Comment by gerth2** [comment]
So ran into weird things turning this into an eclipse project. For now, just adding the javadoc and added a batch file to update the html in the repo. By merging & pushing to the special gh-pages branch, the docs are automatically hosted on github (linked in the wiki)
