### ISSUE TITLE
MethodHandles for logging

### ISSUE THREAD

**Issue by gerth2** [RobotCasserole1736/CasseroleLib#7]
Update CSV Logger to use Nick's MethodHandles implemetation for simplicity.

**Comment by imdunne8** [comment]
I looked over the ways that several teams (including the Poofs) have done logging in the past and I'm pretty convinced that MethodHandles is the cleanest way of making it happen.  We should update my branch with all of the logged methods from this year's robot and run it through a few tests to make sure it all works as expected, but based on my memory and comment on the last commit to it I'm pretty sure it worked with everything that was included at that point.

**Comment by gerth2** [comment]
cloned [this version of the logger](https://github.com/RobotCasserole1736/RobotCasserole2016/blob/NickD_MethodHandles/RobotCasserole2016/src/org/usfirst/frc/team1736/robot/CsvLogger.java) into the repo and removed the non-simple logic for commonality year-to-year. We can add it back in if needed - I can't remember where we left off on this. My preference would be to leave it out and force all data transformations to occur outside the library, but I'm open to discussion on it.

Also, the version of methodHandles csv logging in the repo remains untested. Should probably do that sometime...

**Comment by gerth2** [comment]
Bump update since this hasn't been touched in months. As far as I know, last status was we still needed to do a through test of the cloned logger version

**Comment by gerth2** [comment]
Done.
